'use client'

import { Suspense, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Link, useRouter } from '@/i18n/navigation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert } from '@/components/ui/alert'
import { MIN_PASSWORD_LENGTH } from '@/lib/password-policy'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

export function ResetPasswordPageClient() {
  return (
    <Suspense>
      <ResetPasswordPageInner />
    </Suspense>
  )
}

function ResetPasswordPageInner() {
  const t = useTranslations('auth.resetPassword')
  const tCommon = useTranslations('auth.common')
  const router = useRouter()
  const searchParams = useSearchParams()
  // Both come from the reset-email link generated by the backend's
  // password-reset subscriber: /reset-password?token=...&email=...
  const token = searchParams.get('token') ?? ''
  const email = searchParams.get('email') ?? ''

  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const response = await fetch('/api/auth/reset-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, token, password }),
      })

      const data = await response.json()

      if (!response.ok) {
        setError(data.error || t('failed'))
        return
      }

      // The route signs the customer in with the new password when it can;
      // otherwise fall back to the login form.
      router.push(data.signedIn ? '/account' : '/login')
    } catch {
      setError(tCommon('genericError'))
    } finally {
      setLoading(false)
    }
  }

  const linkIsValid = Boolean(token && email)

  return (
    // Centering and page chrome live in the (auth) layout.
    <div className="w-full max-w-md">
      <Card elevated>
        <CardHeader className="text-center">
          <CardTitle className="text-2xl tracking-tight">
            {t('title')}
          </CardTitle>
          <CardDescription>
            {linkIsValid
              ? t('descriptionValid', { email })
              : t('descriptionInvalid')}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {linkIsValid ? (
            <form onSubmit={handleSubmit} className="space-y-4">
              {error && (
                <Alert tone="critical" role="alert">
                  {error}
                </Alert>
              )}

              <div className="space-y-2">
                <Label htmlFor="password">{tCommon('newPassword')}</Label>
                <Input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  minLength={MIN_PASSWORD_LENGTH}
                  autoComplete="new-password"
                />
                <p className="text-xs text-muted-foreground">
                  {tCommon('passwordHint', { min: MIN_PASSWORD_LENGTH })}
                </p>
              </div>

              <Button type="submit" className="w-full" disabled={loading}>
                {loading ? t('submitting') : t('submit')}
              </Button>
            </form>
          ) : (
            <Alert tone="caution" role="alert">
              {t('invalidLink')}
            </Alert>
          )}
        </CardContent>
        <CardFooter className="justify-center">
          <p className="text-sm text-muted-foreground">
            {linkIsValid ? t('linkExpired') : t('needFreshLink')}{' '}
            <Link
              href="/forgot-password"
              className="text-primary hover:underline"
            >
              {t('requestNew')}
            </Link>
          </p>
        </CardFooter>
      </Card>
    </div>
  )
}
